name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  packages: write
  contents: write

env:
  STUBGEN_BUILD_NUM: 5
  ADDITIONAL_DEFINITION_URLS: |
    https://raw.githubusercontent.com/LuaLink/LuaLinkV2/master/src/main/resources/lua/script.lua
    https://raw.githubusercontent.com/LuaLink/LuaLinkV2/master/src/main/resources/lua/scheduler.lua
  SOURCES_JAR_URLS: |
    https://repo.papermc.io/repository/maven-public/io/papermc/paper/paper-api/1.21.5-no-moonrise-SNAPSHOT/paper-api-1.21.5-no-moonrise-20250328.181903-5-sources.jar

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Download LuaLink/LuaStubGen JAR
        run: |
          # Download to a temporary location
          mkdir -p $RUNNER_TEMP/stubgen
          curl -L -o $RUNNER_TEMP/stubgen/LuaStubGen.jar https://github.com/LuaLink/LuaStubGen/releases/download/$STUBGEN_BUILD_NUM/LuaStubGen-1.0-SNAPSHOT.jar
      - name: Download Source JARs
        run: |
          # Download source JARs
          mkdir -p $RUNNER_TEMP/sources
          IFS=$'\n'  # Split by newline to handle multiple URLs
          for url in $SOURCES_JAR_URLS; do
            filename=$(basename "$url")
            curl -L -o $RUNNER_TEMP/sources/"$filename" "$url"
          done
      - name: Generate Lua definitions
        run: |
          # Generate Lua definitions
          mkdir -p library/paper
          # Get a space separated list of JAR files from the downloaded source JARs
          jar_files=$(ls $RUNNER_TEMP/sources/*.jar | tr '\n' ' ')
          java -jar $RUNNER_TEMP/stubgen/LuaStubGen.jar --output-dir=library/paper $jar_files
      - name: Download additional definitions
        run: |
          # Download additional definitions
          mkdir -p library/lualink
          IFS=$'\n'  # Split by newline to handle multiple URLs
          for url in $ADDITIONAL_DEFINITION_URLS; do
            filename=$(basename "$url")
            curl -L -o library/lualink/"$filename" "$url"
          done
      - name: Commit and push changes
        run: |
          # Commit and push changes
          git config --local user.name "GitHub Action"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com" # Default GitHub Actions bot email
          git add library/paper
          git add library/lualink
          git commit -m "Update Lua definitions" || echo "No changes to commit"
          git push origin HEAD:main
